### ISSUE TITLE
CRUD generated formtype error

### ISSUE THREAD

**Issue by symfonyluxury** [toaotc/ToaTwitterBootstrapBundle#1]
Few days ago symfony master made some changes for form,see:
https://github.com/symfony/symfony/blob/master/UPGRADE-2.1.md#form
so if I follow the upgrade instruction, change the FormBuilder to FormBuilderInterface for function buildForm,
I got this error:
Variable "single_control" does not exist in ***\vendor\toa\twitter-bootstrap-bundle\Toa\Bundle\TwitterBootstrapBundle/Resources/views/Form/widgets.html.twig at line 17
How can I resolve this problem?

**Comment by toaotc** [comment]
Good catch.
Compare [widgets.html.twig](https://github.com/toaotc/ToaTwitterBootstrapBundle/blob/master/Resources/views/Form/widgets.html.twig#L16) and [form_div_layout.html.twig](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L248).
`single_control` was replaced with `compound`.

**Comment by toaotc** [comment]
fixed
