### ISSUE TITLE
Version 2.1 requires "sensio/generator-bundle" in "dev" version whereas there are plenty of stable ones

### ISSUE THREAD

**Issue by turneliusz** [toaotc/ToaTwitterBootstrapBundle#5]
What is the reason? Can it be fixed? I would have to switch my project to "minimum-stability:dev".

**Comment by toaotc** [comment]
Does https://github.com/toaotc/ToaTwitterBootstrapBundle/tree/v2.1.1 fit your needs?

**Comment by turneliusz** [comment]
Exactly, thanks for great bundle!

**Comment by lutzportela** [comment]
Thanks for your advice :)

**Comment by turneliusz** [comment]
No problem, thanks to people like you developing with Symfony 2 is really a pleasure. Thank you again for contribution to community!
