### ISSUE TITLE
Any plan for bootstrap 3.1 integration?

### ISSUE THREAD

**Issue by turneliusz** [toaotc/ToaTwitterBootstrapBundle#6]

**Comment by lutzportela** [comment]
This bundle is just for kickstarting. Anytime i will do the version upgrade.
You can replace `ToaTwitterBootstrapBundle::layout.html.twig` with `app/Resources/ToaTwitterBootstrapBundle/views/layout.html.twig` and change the assets there.

**Comment by toaotc** [comment]
I started the [LayoutBundle](https://github.com/toaotc/LayoutBundle) with Bootstrap3 but without CRUD generator.
